# -*- coding: utf-8 -*-
"""Pilot 5: remaining fichas. Run once: python curacion/pilot5_entries.py"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANUAL = os.path.join(ROOT, 'curacion', 'manual.json')

ENTRIES = {
    "Festo": {"genero": "M", "profesion": "Gobernador romano", "versiculo_clave": "Hechos 25:11", "opinion_jehova": "Gobernador que escuchó a Pablo y lo envió a Roma", "opinion_ref": "Hechos 25:1-12", "cualidades": "Disposición a escuchar; respeto al derecho de apelación", "cualidades_refs": "Hechos 25", "defectos": "Dejó a Pablo preso por complacer a los judíos", "defectos_refs": "Hechos 24:27", "leccion": "La justicia parcial no sustituye una decisión valiente"},
    "Mefibóset": {"genero": "M", "tribu": "Benjamín", "profesion": "Príncipe", "versiculo_clave": "2 Samuel 9:7", "opinion_jehova": "Nieto de Jonatán honrado por David por lealtad al pacto", "opinion_ref": "2 Samuel 9:1-13", "cualidades": "Humildad; gratitud; lealtad", "cualidades_refs": "2 Samuel 9; 2 Samuel 19:24-30", "defectos": "", "defectos_refs": "", "leccion": "La lealtad al pacto puede extenderse con bondad a generaciones futuras"},
    "Ananías": {"genero": "M", "profesion": "Discípulo", "versiculo_clave": "Hechos 5:3-4", "opinion_jehova": "Mentir al espíritu santo trajo juicio inmediato", "opinion_ref": "Hechos 5:1-11", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Engaño; hipocresía; codicia", "defectos_refs": "Hechos 5:1-10", "leccion": "Jehová detesta la deshonestidad en el servicio sagrado"},
    "Félix": {"genero": "M", "profesion": "Gobernador romano", "versiculo_clave": "Hechos 24:25", "opinion_jehova": "Escuchó a Pablo pero pospuso la decisión por conveniencia", "opinion_ref": "Hechos 24:24-27", "cualidades": "Reconoció la enseñanza de Pablo", "cualidades_refs": "Hechos 24:24-25", "defectos": "Procrastinación; esperaba sobornos; mantuvo a Pablo preso", "defectos_refs": "Hechos 24:26-27", "leccion": "Posponer la respuesta a la verdad puede ser tan dañino como rechazarla"},
    "Belsasar": {"genero": "M", "profesion": "Rey de Babilonia", "versiculo_clave": "Daniel 5:30", "opinion_jehova": "Rey que profanó los utensilios del templo y fue juzgado esa noche", "opinion_ref": "Daniel 5:1-30", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Profanación; orgullo; banquete sacrílego", "defectos_refs": "Daniel 5", "leccion": "Despreciar lo sagrado de Jehová trae juicio repentino"},
    "Marta": {"genero": "F", "profesion": "Discípula", "versiculo_clave": "Lucas 10:41-42", "opinion_jehova": "Amiga de Jesús que aprendió a valorar lo espiritual", "opinion_ref": "Lucas 10:38-42; Juan 11:5", "cualidades": "Hospitalidad; servicio; fe en la resurrección", "cualidades_refs": "Lucas 10; Juan 11:20-27", "defectos": "Se preocupaba demasiado por muchas cosas", "defectos_refs": "Lucas 10:41", "leccion": "Escoger lo mejor es sentarse a los pies de Cristo para aprender"},
    "Sísara": {"genero": "M", "profesion": "Militar", "profesion_2": "Comandante cananeo", "versiculo_clave": "Jueces 4:9", "opinion_jehova": "Enemigo oprimidor de Israel derrotado por el ejército de Jehová", "opinion_ref": "Jueces 4:12-16", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Oppresión; arrogancia militar", "defectos_refs": "Jueces 4", "leccion": "Los opresores de el pueblo de Jehová no prevalecen"},
    "Ciro": {"genero": "M", "profesion": "Rey", "profesion_2": "Emperador persa", "versiculo_clave": "Isaías 45:1", "opinion_jehova": "Ungido de Jehová para liberar a los judíos del exilio", "opinion_ref": "Isaías 45:1-4; 2 Crónicas 36:22-23", "cualidades": "Cumplió el decreto de retorno; respeto al mandato divino", "cualidades_refs": "Esdras 1:1-4", "defectos": "", "defectos_refs": "", "leccion": "Jehová puede usar gobernantes extranjeros para cumplir sus profecías"},
    "Darío": {"genero": "M", "profesion": "Rey", "profesion_2": "Emperador medo-persa", "versiculo_clave": "Daniel 6:16", "opinion_jehova": "Rey que reconoció el Dios viviente tras el milagro con Daniel", "opinion_ref": "Daniel 6:25-27", "cualidades": "Reconoció el poder de Jehová; respeto a Daniel", "cualidades_refs": "Daniel 6", "defectos": "Firmó un decreto imprudente por orgullo", "defectos_refs": "Daniel 6:6-9", "leccion": "Las leyes humanas no pueden anular la protección de Jehová"},
    "Asuero": {"genero": "M", "profesion": "Rey", "profesion_2": "Emperador persa", "versiculo_clave": "Ester 8:8", "opinion_jehova": "Monarca persa instrumento para salvar al pueblo de Jehová", "opinion_ref": "Ester 2:17; Ester 8", "cualidades": "Elevó a Ester; respondió al decreto de Hamán", "cualidades_refs": "Ester 2; Ester 8", "defectos": "Decretó exterminio sin investigar; banquetes prolongados", "defectos_refs": "Ester 3; Ester 1", "leccion": "Jehová puede usar imperios humanos para proteger a su pueblo"},
    "Balaam": {"genero": "M", "profesion": "Profeta", "versiculo_clave": "Números 22:18", "opinion_jehova": "Profeta que reconoció a Jehová pero fue seducido por la codicia", "opinion_ref": "Números 22:18; 2 Pedro 2:15", "cualidades": "Conocía el nombre de Jehová; profetizó bendiciones a Israel", "cualidades_refs": "Números 23-24", "defectos": "Codicia; aconsejó apostasía a Balac; ambición", "defectos_refs": "Números 31:16; Apocalipsis 2:14", "leccion": "Conocer la verdad sin obedecerla conduce a la ruina"},
    "Jairo": {"genero": "M", "profesion": "Jefe de sinagoga", "versiculo_clave": "Marcos 5:23", "opinion_jehova": "Padre que buscó a Jesús con fe desesperada por su hija", "opinion_ref": "Marcos 5:22-43", "cualidades": "Fe; humildad; persistencia", "cualidades_refs": "Marcos 5; Lucas 8:41-56", "defectos": "", "defectos_refs": "", "leccion": "Acudir a Jesús con fe puede restaurar lo que parece perdido"},
    "Satanás": {"genero": "M", "profesion": "Adversario", "versiculo_clave": "Mateo 4:10", "opinion_jehova": "Adversario que tentó a Jesús y fue rechazado con las Escrituras", "opinion_ref": "Mateo 4:1-11; Apocalipsis 12:9", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Engaño; rebelión; tentación", "defectos_refs": "Génesis 3; Mateo 4", "leccion": "Responder con las Escrituras es la defensa contra la tentación"},
    "Demetrio": {"genero": "M", "profesion": "Artesano", "versiculo_clave": "Hechos 19:25", "opinion_jehova": "Plataformista que provocó disturbio por intereses comerciales", "opinion_ref": "Hechos 19:24-27", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Codicia; incitar multitudes contra la verdad", "defectos_refs": "Hechos 19", "leccion": "Los intereses materiales pueden cegar contra el mensaje del Reino"},
    "Rehoboam": {"genero": "M", "tribu": "Judá", "profesion": "Rey", "versiculo_clave": "1 Reyes 12:8", "opinion_jehova": "Rey cuyo orgullo dividió el reino de Israel", "opinion_ref": "1 Reyes 12:1-19", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Arrogancia; rechazó consejo sabio; dividió la nación", "defectos_refs": "1 Reyes 12", "leccion": "Despreciar el buen consejo puede destruir lo que se hereda"},
    "Anás": {"genero": "M", "profesion": "Sumo sacerdote", "versiculo_clave": "Juan 18:13", "opinion_jehova": "Sumo sacerdote que participó en el juicio contra Jesús", "opinion_ref": "Juan 18:13; Lucas 3:2", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Corrupción sacerdotal; conspiración contra el Mesías", "defectos_refs": "Juan 18", "leccion": "El cargo religioso no garantiza integridad ante Dios"},
    "Herodes el Grande": {"genero": "M", "profesion": "Rey", "versiculo_clave": "Mateo 2:16", "opinion_jehova": "Rey que masacró niños intentando matar al Mesías", "opinion_ref": "Mateo 2:16-18", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Crueldad extrema; paranoia; violencia", "defectos_refs": "Mateo 2", "leccion": "La violencia contra los siervos de Dios no detiene su propósito"},
    "Absalón": {"genero": "M", "tribu": "Judá", "profesion": "Príncipe", "versiculo_clave": "2 Samuel 15:6", "opinion_jehova": "Hijo de David que usurpó el trono y murió en rebelión", "opinion_ref": "2 Samuel 15-18", "cualidades": "Carisma superficial; belleza física", "cualidades_refs": "2 Samuel 14:25", "defectos": "Ambición; venganza; rebelión; adulterio", "defectos_refs": "2 Samuel 13; 2 Samuel 15", "leccion": "La ambición sin integridad destruye familias y naciones"},
    "Míriam": {"genero": "F", "tribu": "Leví", "profesion": "Profetisa", "versiculo_clave": "Éxodo 15:20", "opinion_jehova": "Profetisa que celebró la liberación en el mar Rojo", "opinion_ref": "Éxodo 15:20-21; Números 12:1-2", "cualidades": "Liderazgo; alabanza; protección del bebé Moisés", "cualidades_refs": "Éxodo 2:4-8; Éxodo 15", "defectos": "Envidia y oposición a Moisés", "defectos_refs": "Números 12:1-10", "leccion": "Incluso líderes usados por Jehová deben guardarse de la envidia"},
    "Balac": {"genero": "M", "profesion": "Rey", "versiculo_clave": "Números 22:6", "opinion_jehova": "Rey de Moab que intentó maldecir a Israel", "opinion_ref": "Números 22:2-6; Apocalipsis 2:14", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Miedo; intento de maldecir al pueblo de Dios", "defectos_refs": "Números 22-24", "leccion": "Nadie puede maldecir a quien Jehová ha bendecido"},
    "Senaquerib": {"genero": "M", "profesion": "Rey", "profesion_2": "Emperador asirio", "versiculo_clave": "2 Reyes 19:35", "opinion_jehova": "Enemigo que blasfemó contra Jehová y fue derrotado milagrosamente", "opinion_ref": "2 Reyes 19:20-37", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Blasfemia; arrogancia; amenazas contra Jerusalén", "defectos_refs": "2 Reyes 18-19", "leccion": "Jehová defiende su nombre y su pueblo ante enemigos soberbios"},
    "Zorobabel": {"genero": "M", "tribu": "Judá", "profesion": "Gobernador", "versiculo_clave": "Hageo 2:23", "opinion_jehova": "Líder del retorno del exilio y la reconstrucción del templo", "opinion_ref": "Esdras 3:2; Hageo 2:21-23", "cualidades": "Obediencia; liderazgo; perseverancia", "cualidades_refs": "Esdras 3-6; Hageo 1", "defectos": "", "defectos_refs": "", "leccion": "No despreciar los comienzos modestos de la obra de Jehová"},
    "Barrabás": {"genero": "M", "profesion": "Rebelde", "versiculo_clave": "Mateo 27:16", "opinion_jehova": "Criminal liberado en lugar del Mesías inocente", "opinion_ref": "Mateo 27:15-26", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Violencia; sedición; homicidio", "defectos_refs": "Mateo 27:16; Marcos 15:7", "leccion": "Las multitudes pueden preferir al culpable sobre al justo"},
    "Alejandro Magno": {"genero": "M", "profesion": "Rey", "profesion_2": "Conquistador", "versiculo_clave": "Daniel 8:21", "opinion_jehova": "Conquistador profetizado en la visión de las bestias", "opinion_ref": "Daniel 8:5-8; Daniel 11:3-4", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Conquista violenta; imperio efímero", "defectos_refs": "Daniel 8", "leccion": "Los imperios humanos pasan; el Reino de Dios permanece"},
    "Amnón": {"genero": "M", "tribu": "Judá", "profesion": "Príncipe", "versiculo_clave": "2 Samuel 13:14", "opinion_jehova": "Hijo de David que cometió grave violencia y fue castigado", "opinion_ref": "2 Samuel 13:1-29", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Lujuria; violencia; falta de arrepentimiento", "defectos_refs": "2 Samuel 13", "leccion": "El pecado no corregido genera más dolor en la familia"},
    "Sadoc": {"genero": "M", "tribu": "Leví", "profesion": "Sumo sacerdote", "versiculo_clave": "1 Reyes 1:39", "opinion_jehova": "Sacerdote leal que ungió a Salomón como rey", "opinion_ref": "1 Reyes 1:32-39", "cualidades": "Lealtad a David y a la voluntad de Jehová", "cualidades_refs": "1 Reyes 1", "defectos": "", "defectos_refs": "", "leccion": "Apoyar al sucesor designado por Jehová evita divisiones"},
    "Goliat": {"genero": "M", "profesion": "Guerrero", "profesion_2": "Gigante filisteo", "versiculo_clave": "1 Samuel 17:45", "opinion_jehova": "Gigante que desafió al ejército de Israel y fue vencido por David", "opinion_ref": "1 Samuel 17:4-51", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Arrogancia; desafío a Jehová", "defectos_refs": "1 Samuel 17", "leccion": "La fe en Jehová vence enemigos que parecen invencibles"},
    "Mical": {"genero": "F", "tribu": "Benjamín", "profesion": "Princesa", "profesion_2": "Esposa de David", "versiculo_clave": "2 Samuel 6:16", "opinion_jehova": "Hija de Saúl que despreció a David por su alegría espiritual", "opinion_ref": "2 Samuel 6:16-23", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Desprecio hacia la adoración sincera de David", "defectos_refs": "2 Samuel 6:20", "leccion": "Menospreciar la adoración sincera aleja de las bendiciones"},
    "Bat-seba": {"genero": "F", "profesion": "Reina", "versiculo_clave": "2 Samuel 12:24", "opinion_jehova": "Esposa de David; madre de Salomón tras el arrepentimiento", "opinion_ref": "2 Samuel 12:24; 1 Reyes 1:11-31", "cualidades": "Madre protectora de Salomón; apoyo en la sucesión", "cualidades_refs": "1 Reyes 1", "defectos": "Participó en el adulterio inicial con David", "defectos_refs": "2 Samuel 11", "leccion": "Jehová puede restaurar tras el arrepentimiento genuino"},
    "Urías": {"genero": "M", "profesion": "Soldado", "versiculo_clave": "2 Samuel 11:11", "opinion_jehova": "Guerrero leal injustamente asesinado por orden de David", "opinion_ref": "2 Samuel 11:11-17", "cualidades": "Lealtad al rey y al ejército; integridad", "cualidades_refs": "2 Samuel 11:11", "defectos": "", "defectos_refs": "", "leccion": "La injusticia contra siervos fieles no queda sin respuesta de Jehová"},
    "Joab": {"genero": "M", "profesion": "Militar", "profesion_2": "General", "versiculo_clave": "2 Samuel 3:39", "opinion_jehova": "General de David valiente pero violento y ambicioso", "opinion_ref": "2 Samuel 3:39; 1 Reyes 2:5-6", "cualidades": "Valentía militar; lealtad parcial a David", "cualidades_refs": "2 Samuel 8; 2 Samuel 10", "defectos": "Asesinatos por venganza; desobedeció órdenes de David", "defectos_refs": "2 Samuel 3:27; 2 Samuel 18:14", "leccion": "El talento sin sumisión a Jehová corrompe el servicio"},
    "Hiram": {"genero": "M", "profesion": "Rey", "profesion_2": "Rey de Tiro", "versiculo_clave": "1 Reyes 5:12", "opinion_jehova": "Aliado de Salomón en la construcción del templo", "opinion_ref": "1 Reyes 5:1-12", "cualidades": "Cooperación; suministro de materiales y artesanos", "cualidades_refs": "1 Reyes 5; 2 Crónicas 2", "defectos": "", "defectos_refs": "", "leccion": "Jehová puede usar aliados extranjeros para obras sagradas"},
    "reina de Seba": {"genero": "F", "profesion": "Reina", "versiculo_clave": "1 Reyes 10:9", "opinion_jehova": "Monarca extranjera que reconoció la sabiduría dada por Jehová a Salomón", "opinion_ref": "1 Reyes 10:1-9", "cualidades": "Búsqueda de sabiduría; reconocimiento de Jehová", "cualidades_refs": "1 Reyes 10", "defectos": "", "defectos_refs": "", "leccion": "La sabiduría de Jehová atrae a buscadores sinceros de todo el mundo"},
    "Gad": {"genero": "M", "profesion": "Profeta", "versiculo_clave": "2 Samuel 24:11-13", "opinion_jehova": "Profeta que transmitió las opciones de castigo a David", "opinion_ref": "2 Samuel 24:11-14", "cualidades": "Fidelidad profética; claridad", "cualidades_refs": "2 Samuel 24; 1 Crónicas 21", "defectos": "", "defectos_refs": "", "leccion": "Los profetas deben transmitir mensajes difíciles con fidelidad"},
    "Amram": {"genero": "M", "tribu": "Leví", "profesion": "Patriarca levita", "versiculo_clave": "Éxodo 6:20", "opinion_jehova": "Padre de Moisés, Aarón y Míriam", "opinion_ref": "Éxodo 6:20", "cualidades": "Formó una familia usada por Jehová", "cualidades_refs": "Éxodo 6", "defectos": "", "defectos_refs": "", "leccion": "La fe en la familia prepara instrumentos para la liberación"},
    "Coré": {"genero": "M", "tribu": "Leví", "profesion": "Levita", "versiculo_clave": "Números 16:11", "opinion_jehova": "Lideró una rebelión contra Moisés y Aarón", "opinion_ref": "Números 16:1-35", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Ambición; rebelión contra el orden de Jehová", "defectos_refs": "Números 16", "leccion": "Rebelarse contra el arreglo de Jehová trae destrucción"},
    "Hananiás, Misael y Azariás": {"genero": "M", "profesion": "Jóvenes fieles", "versiculo_clave": "Daniel 3:17-18", "opinion_jehova": "Compañeros de Daniel que no adoraron la imagen de oro", "opinion_ref": "Daniel 3:16-30", "opinion_cita": "Nuestro Dios a quien servimos puede librarnos. Pero, aunque no lo haga, no serviremos a tu dios.", "cualidades": "Fe inquebrantable; valentía; unidad", "cualidades_refs": "Daniel 3", "defectos": "", "defectos_refs": "", "leccion": "Obedecer a Jehová aunque cueste la vida"},
    "Roboam": {"genero": "M", "tribu": "Judá", "profesion": "Rey", "versiculo_clave": "1 Reyes 12:8", "opinion_jehova": "Rey que dividió Israel por orgullo (mismo suceso que Rehoboam)", "opinion_ref": "1 Reyes 12:1-19", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Arrogancia; rechazó consejo sabio", "defectos_refs": "1 Reyes 12", "leccion": "El orgullo destruye lo que se hereda"},
    "Saraí": {"genero": "F", "profesion": "Patriarca", "versiculo_clave": "Génesis 17:15", "opinion_jehova": "Esposa de Abrahán; nombre cambiado cuando se confirmó la promesa", "opinion_ref": "Génesis 17:15-16", "cualidades": "Fe que maduró (ver también Sara)", "cualidades_refs": "Génesis 17-18", "defectos": "Ver entrada curada de Sara", "defectos_refs": "Génesis 16", "leccion": "Jehová renueva las promesas a quienes confían en él"},
    "Bezaleel": {"genero": "M", "tribu": "Judá", "profesion": "Artesano", "versiculo_clave": "Éxodo 31:3", "opinion_jehova": "Lleno del espíritu de Dios para construir el tabernáculo", "opinion_ref": "Éxodo 31:1-6; Éxodo 36:1-2", "cualidades": "Habilidad; obediencia; liderazgo artesanal", "cualidades_refs": "Éxodo 31; Éxodo 36", "defectos": "", "defectos_refs": "", "leccion": "Jehová capacita a siervos hábiles para su obra de adoración"},
    "Acán": {"genero": "M", "tribu": "Judá", "profesion": "Soldado", "versiculo_clave": "Josué 7:20-21", "opinion_jehova": "Su codicia trajo derrota a Israel en Hai", "opinion_ref": "Josué 7:1-26", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Codicia; desobediencia; mentira", "defectos_refs": "Josué 7", "leccion": "El pecado oculto de uno puede afectar a toda la congregación"},
    "Elcaná": {"genero": "M", "tribu": "Efraín", "profesion": "Patriarca", "versiculo_clave": "1 Samuel 1:5", "opinion_jehova": "Padre de Samuel; esposo fiel de Ana", "opinion_ref": "1 Samuel 1:1-28", "cualidades": "Peregrinación regular a Silo; amor a Ana", "cualidades_refs": "1 Samuel 1", "defectos": "", "defectos_refs": "", "leccion": "La adoración familiar prepara el camino para siervos de Jehová"},
    "Ajías": {"genero": "M", "profesion": "Profeta", "versiculo_clave": "1 Reyes 11:29-31", "opinion_jehova": "Profeta que anunció la división del reino por la apostasía de Salomón", "opinion_ref": "1 Reyes 11:29-39", "cualidades": "Valentía profética; obediencia", "cualidades_refs": "1 Reyes 11", "defectos": "", "defectos_refs": "", "leccion": "Los profetas declaran las consecuencias de la desobediencia real"},
    "Nabot": {"genero": "M", "profesion": "Propietario de viña", "versiculo_clave": "1 Reyes 21:3", "opinion_jehova": "Justo que rechazó vender su herencia y fue asesinado", "opinion_ref": "1 Reyes 21:1-19", "cualidades": "Integridad; respeto por la herencia de Jehová", "cualidades_refs": "1 Reyes 21:3", "defectos": "", "defectos_refs": "", "leccion": "Jehová defiende a quienes no venden su integridad"},
    "Hilcías": {"genero": "M", "profesion": "Sumo sacerdote", "versiculo_clave": "2 Reyes 22:8", "opinion_jehova": "Encontró el libro de la Ley durante las reformas de Josías", "opinion_ref": "2 Reyes 22:8-11", "cualidades": "Fidelidad; celo por redescubrir la Palabra", "cualidades_refs": "2 Reyes 22", "defectos": "", "defectos_refs": "", "leccion": "Redescubrir la Palabra de Dios puede iniciar grandes reformas"},
    "Haggeo": {"genero": "M", "profesion": "Profeta", "versiculo_clave": "Hageo 1:8", "opinion_jehova": "Animó a Zorobabel y Josué a reconstruir el templo", "opinion_ref": "Hageo 1:1-15; Hageo 2:1-9", "cualidades": "Ánimo; celo por la casa de Jehová", "cualidades_refs": "Hageo 1-2", "defectos": "", "defectos_refs": "", "leccion": "Priorizar la obra de Jehová trae bendición"},
    "Satán": {"genero": "M", "profesion": "Adversario", "versiculo_clave": "Job 1:12", "opinion_jehova": "Acusador que puso a prueba la integridad de Job", "opinion_ref": "Job 1:6-12; Job 2:4-7", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Acusación; provocación; engaño", "defectos_refs": "Job 1-2", "leccion": "Jehová limita las pruebas y vindica a los íntegros"},
    "Safira": {"genero": "F", "profesion": "Discípula", "versiculo_clave": "Hechos 5:9", "opinion_jehova": "Participó con Ananías en el engaño sobre una venta", "opinion_ref": "Hechos 5:1-10", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Complicidad en el engaño", "defectos_refs": "Hechos 5:1-10", "leccion": "La deshonestidad compartida no reduce la responsabilidad personal"},
    "Jokébed": {"genero": "F", "tribu": "Leví", "profesion": "Madre", "versiculo_clave": "Éxodo 2:2-3", "opinion_jehova": "Madre valiente que preservó la vida de Moisés", "opinion_ref": "Éxodo 2:1-10; Hebreos 11:23", "cualidades": "Fe; valentía; amor maternal", "cualidades_refs": "Éxodo 2; Hebreos 11:23", "defectos": "", "defectos_refs": "", "leccion": "La fe de una madre puede cambiar el destino de una nación"},
    "Jeroboán (I)": {"genero": "M", "tribu": "Efraín", "profesion": "Rey", "versiculo_clave": "1 Reyes 12:28-30", "opinion_jehova": "Primer rey del norte que estableció culto ilegítimo (ver Jeroboán)", "opinion_ref": "1 Reyes 12:26-33", "cualidades": "Ninguna fiel destacada en las Escrituras", "cualidades_refs": "", "defectos": "Apostasía; becerros de oro", "defectos_refs": "1 Reyes 12", "leccion": "Ver ficha curada de Jeroboán"},
    "Eleazar": {"genero": "M", "tribu": "Leví", "profesion": "Sumo sacerdote", "versiculo_clave": "Números 20:28", "opinion_jehova": "Sucesor de Aarón como sumo sacerdote", "opinion_ref": "Números 20:25-28", "cualidades": "Servicio sacerdotal fiel", "cualidades_refs": "Números 20", "defectos": "", "defectos_refs": "", "leccion": "Jehová designa sucesores para continuar el servicio sagrado"},
    "Finehás": {"genero": "M", "tribu": "Leví", "profesion": "Sacerdote", "versiculo_clave": "Números 25:11", "opinion_jehova": "Mostró celo ardiente y recibió pacto de paz sacerdotal", "opinion_ref": "Números 25:11-13", "cualidades": "Celo por la pureza del pueblo", "cualidades_refs": "Números 25", "defectos": "", "defectos_refs": "", "leccion": "El celo por la pureza de la adoración es valorado por Jehová"},
    "Abiatar": {"genero": "M", "tribu": "Leví", "profesion": "Sumo sacerdote", "versiculo_clave": "1 Samuel 22:20", "opinion_jehova": "Sacerdote leal a David; único sobreviviente de la masacre de Nob", "opinion_ref": "1 Samuel 22:20-23", "cualidades": "Lealtad a David en la persecución", "cualidades_refs": "1 Samuel 22-23", "defectos": "Apoyó a Adonías contra Salomón", "defectos_refs": "1 Reyes 1:7-25", "leccion": "La lealtad inicial debe sostenerse hasta el final del servicio"},
    "Asaf": {"genero": "M", "tribu": "Leví", "profesion": "Músico", "profesion_2": "Profeta", "versiculo_clave": "Salmo 73:1", "opinion_jehova": "Líder de los cantores del templo; autor de salmos", "opinion_ref": "1 Crónicas 16:4-7; Salmo 50", "cualidades": "Adoración; enseñanza poética", "cualidades_refs": "Salmos de Asaf", "defectos": "", "defectos_refs": "", "leccion": "La música puede enseñar profundas verdades teológicas"},
    "Jedutún": {"genero": "M", "tribu": "Leví", "profesion": "Músico", "versiculo_clave": "1 Crónicas 16:41", "opinion_jehova": "Cantor designado para la adoración en el tabernáculo", "opinion_ref": "1 Crónicas 16:41-42", "cualidades": "Servicio musical dedicado", "cualidades_refs": "1 Crónicas 16", "defectos": "", "defectos_refs": "", "leccion": "La adoración musical honra a Jehová cuando es sincera"},
    "Juan Marcos": {"genero": "M", "profesion": "Evangelista", "versiculo_clave": "2 Timoteo 4:11", "opinion_jehova": "Alias de Marcos, compañero de Pablo y Bernabé (ver ficha Marcos)", "opinion_ref": "Hechos 12:25; Hechos 15:37", "cualidades": "Ver ficha curada de Marcos", "cualidades_refs": "Hechos 12", "defectos": "Ver ficha curada de Marcos", "defectos_refs": "Hechos 13:13", "leccion": "Ver ficha curada de Marcos"},
    "Sadrac": {"genero": "M", "profesion": "Joven fiel", "versiculo_clave": "Daniel 3:17", "opinion_jehova": "Ver Hananías, Misael y Azariás (Sadrac = Azariás)", "opinion_ref": "Daniel 3", "cualidades": "Ver Hananías, Misael y Azariás", "cualidades_refs": "Daniel 3", "defectos": "", "defectos_refs": "", "leccion": "Ver Hananías, Misael y Azariás"},
    "Mesac": {"genero": "M", "profesion": "Joven fiel", "versiculo_clave": "Daniel 3:17", "opinion_jehova": "Ver Hananías, Misael y Azariás (Mesac = Misael)", "opinion_ref": "Daniel 3", "cualidades": "Ver Hananías, Misael y Azariás", "cualidades_refs": "Daniel 3", "defectos": "", "defectos_refs": "", "leccion": "Ver Hananías, Misael y Azariás"},
    "Abednego": {"genero": "M", "profesion": "Joven fiel", "versiculo_clave": "Daniel 3:17", "opinion_jehova": "Ver Hananías, Misael y Azariás (Abednego = Hananías)", "opinion_ref": "Daniel 3", "cualidades": "Ver Hananías, Misael y Azariás", "cualidades_refs": "Daniel 3", "defectos": "", "defectos_refs": "", "leccion": "Ver Hananías, Misael y Azariás"},
    "Juan": {"genero": "M", "profesion": "Apóstol", "versiculo_clave": "Juan 13:23", "opinion_jehova": "Alias de Juan el apóstol (ver ficha curada)", "opinion_ref": "Juan 21:20-24", "cualidades": "Ver ficha Juan el apóstol", "cualidades_refs": "1 Juan 4", "defectos": "Ver ficha Juan el apóstol", "defectos_refs": "Lucas 9:54", "leccion": "Ver ficha Juan el apóstol"},
    "Saulo": {"genero": "M", "profesion": "Apóstol", "versiculo_clave": "Hechos 9:15", "opinion_jehova": "Nombre hebreo de Pablo antes de su conversión (ver ficha Pablo)", "opinion_ref": "Hechos 9:4-6", "cualidades": "Ver ficha Pablo", "cualidades_refs": "Gálatas 1:13", "defectos": "Ver ficha Pablo", "defectos_refs": "Hechos 8:3", "leccion": "Ver ficha Pablo"},
    "Felipe": {"genero": "M", "profesion": "Apóstol", "versiculo_clave": "Juan 1:45", "opinion_jehova": "Apóstol que llevó a Natanael a Jesús (distinto de Felipe el evangelizador)", "opinion_ref": "Juan 1:43-46; Juan 6:5-7", "cualidades": "Evangelizador; servicio práctico", "cualidades_refs": "Juan 1; Juan 12:21-22", "defectos": "", "defectos_refs": "", "leccion": "Invitar a otros a conocer a Cristo es un servicio valioso"},
    "Jesucristo": {"genero": "M", "profesion": "Mesías", "versiculo_clave": "Juan 8:29", "opinion_jehova": "Ver ficha curada de Jesús", "opinion_ref": "Mateo 3:17", "cualidades": "Ver ficha Jesús", "cualidades_refs": "Juan 13:15", "defectos": "", "defectos_refs": "", "leccion": "Ver ficha Jesús"},
}

def main():
    with open(MANUAL, encoding='utf-8') as f:
        data = json.load(f)
    entries = data.setdefault('entries', {})
    added = updated = 0
    for name, patch in ENTRIES.items():
        if name in entries:
            entries[name].update(patch)
            updated += 1
        else:
            entries[name] = patch
            added += 1
    data['version'] = 1
    with open(MANUAL, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write('\n')
    print(f'Pilot 5 merged: {added} added, {updated} updated, total {len(entries)}')

if __name__ == '__main__':
    main()
