# -*- coding: utf-8 -*-
"""Genera curacion/nt_escritura.json combinando cabeceras extraídas de los PDFs
y el contenido (propósito/contexto/datos) curado por subagentes."""
import json, os, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# (escritor, lugar, lugar_incerto, inicio, fin, ini_est, fin_est, hecho_id, nombre, personajes, tipo, referencia)
CAB = {
 'MATEO': ('Mateo','Palestina',False,41,41,True,True,None,'Evangelio según Mateo','Mateo','redacción/evangelio','Mateo 1:1'),
 'MARCOS': ('Marcos','Roma',False,60,65,True,True,None,'Evangelio según Marcos','Marcos','redacción/evangelio','Marcos 1:1'),
 'LUCAS': ('Lucas','Cesarea',False,56,58,True,True,None,'Evangelio según Lucas','Lucas','redacción/evangelio','Lucas 1:3'),
 'JUAN': ('El apóstol Juan','Éfeso, o cerca',True,98,98,True,True,None,'Evangelio según Juan','Juan','redacción/evangelio','Juan 20:31'),
 'HECHOS': ('Lucas','Roma',False,61,61,True,True,None,'Hechos de los Apóstoles','Lucas','redacción','Hechos 1:1'),
 'ROMANOS': ('Pablo','Corinto',False,56,56,True,True,189,'Carta a los Romanos','Pablo','redacción/epístola','Romanos 1:1'),
 '1 CORINTIOS': ('Pablo','Éfeso',False,55,55,True,True,160,'Primera carta a los Corintios','Pablo, Corintios','redacción/epístola','1 Corintios 1:2'),
 '2 CORINTIOS': ('Pablo','Macedonia',False,55,55,True,True,165,'Segunda carta a los Corintios','Pablo, Corintios','redacción/epístola','2 Corintios 1:1'),
 'GÁLATAS': ('Pablo','Corinto o Antioquía de Siria',True,50,52,True,True,178,'Carta a los Gálatas','Pablo, Gálatas','redacción/epístola','Gálatas 1:2'),
 'EFESIOS': ('Pablo','Roma',False,60,61,True,True,175,'Carta a los Efesios','Pablo, Efesios','redacción/epístola','Efesios 1:1'),
 'FILIPENSES': ('Pablo','Roma',False,60,61,True,True,177,'Carta a los Filipenses','Pablo, Filipenses','redacción/epístola','Filipenses 1:1'),
 'COLOSENSES': ('Pablo','Roma',False,60,61,True,True,174,'Carta a los Colosenses','Pablo, Colosenses','redacción/epístola','Colosenses 1:2'),
 '1 TESALONICENSES': ('Pablo','Corinto',False,50,50,True,True,163,'Primera carta a los Tesalonicenses','Pablo, Tesalonicenses','redacción/epístola','1 Tesalonicenses 1:1'),
 '2 TESALONICENSES': ('Pablo','Corinto',False,51,51,True,True,168,'Segunda carta a los Tesalonicenses','Pablo, Tesalonicenses','redacción/epístola','2 Tesalonicenses 1:1'),
 '1 TIMOTEO': ('Pablo','Macedonia',False,61,64,True,True,164,'Primera carta a Timoteo','Pablo, Timoteo','redacción/epístola','1 Timoteo 1:2'),
 '2 TIMOTEO': ('Pablo','Roma',False,65,65,True,True,169,'Segunda carta a Timoteo','Pablo, Timoteo','redacción/epístola','2 Timoteo 1:2'),
 'TITO': ('Pablo','Macedonia',True,61,64,True,True,192,'Carta a Tito','Pablo, Tito','redacción/epístola','Tito 1:4'),
 'FILEMÓN': ('Pablo','Roma',False,60,61,True,True,176,'Carta a Filemón','Pablo, Filemón','redacción/epístola','Filemón 1:1'),
 'HEBREOS': ('Pablo','Roma',False,61,61,True,True,181,'Carta a los Hebreos','Pablo','redacción/epístola','Hebreos 1:1'),
 'SANTIAGO': ('Santiago','Jerusalén',False,62,62,True,True,190,'Carta de Santiago','Santiago','redacción/epístola','Santiago 1:1'),
 '1 PEDRO': ('Pedro','Babilonia',False,62,64,True,True,162,'Primera carta de Pedro','Pedro','redacción/epístola','1 Pedro 1:1'),
 '2 PEDRO': ('Pedro','Babilonia',True,64,64,True,True,167,'Segunda carta de Pedro','Pedro','redacción/epístola','2 Pedro 1:1'),
 '1 JUAN': ('El apóstol Juan','Éfeso, o cerca',True,98,98,True,True,161,'Primera carta de Juan','Juan','redacción/epístola','1 Juan 1:1'),
 '2 JUAN': ('El apóstol Juan','Éfeso, o cerca',True,98,98,True,True,166,'Segunda carta de Juan','Juan','redacción/epístola','2 Juan 1:1'),
 '3 JUAN': ('El apóstol Juan','Éfeso, o cerca',True,98,98,True,True,170,'Tercera carta de Juan','Juan','redacción/epístola','3 Juan 1:1'),
 'JUDAS': ('Judas','Palestina',True,65,65,True,True,183,'Carta de Judas','Judas','redacción/epístola','Judas 1:1'),
 'APOCALIPSIS': ('El apóstol Juan','Patmos',False,96,96,True,True,None,'Revelación (Apocalipsis)','Juan','redacción/apocalipsis','Revelación 1:9'),
}

# contenido curado por subagentes: {libro: {proposito, contexto_historico, datos_interesantes}}
CONTI = {
 'MATEO': {"proposito":"Probar ante los judíos que Jesús es el Mesías y Rey prometido del Reino de Dios.","contexto_historico":"Escrito por Mateo, ex recaudador de impuestos, en Palestina alrededor del año 41 E.C., probablemente primero en hebreo y luego traducido al griego.","datos_interesantes":["Escrito principalmente para los judíos, como muestran su genealogía desde Abrahán y sus numerosas referencias a las Escrituras Hebreas.","Es el primero y uno de los evangelios sinópticos; el 42 % de su relato no aparece en los otros tres.","Recalca el tema del «reino de los cielos», usando el término «reino» más de 50 veces.","Su autoría la atribuyen unánimemente los historiadores eclesiásticos primitivos, desde Papías (s. II)."]},
 'MARCOS': {"proposito":"Presentar a Jesús como el Hijo de Dios que hace milagros, un Salvador victorioso, enfocándose en sus obras.","contexto_historico":"Escrito por Marcos desde Roma entre 60 y 65 E.C., con Pedro como su principal fuente de información.","datos_interesantes":["Escrito principalmente para lectores romanos, lo que se nota por las explicaciones de costumbres judías y el uso de términos latinos.","Es el más breve de los cuatro evangelios, rico en acción, y menciona al menos 19 milagros.","Según Papías, Orígenes y Tertuliano, Pedro fue su fuente de los detalles íntimos del relato.","Las conclusiones larga y corta tras Marcos 16:8 no se consideran auténticas; faltan en manuscritos antiguos."]},
 'LUCAS': {"proposito":"Escribir un relato investigado con exactitud y en orden lógico para que Teófilo conociera con plena certeza los hechos.","contexto_historico":"Escrito por Lucas, el médico amado, en Cesarea alrededor de 56-58 E.C., mientras esperaba con Pablo antes del viaje a Roma.","datos_interesantes":["El 59 % de su evangelio no aparece en los demás relatos; es el más largo de los cuatro.","Emplea más de 300 términos médicos o con significado médico, reflejo de su formación como médico.","Se distingue por su exactitud histórica, citando hasta siete funcionarios públicos para fechar los ministerios.","Confirma la profecía de Jesús sobre la destrucción de Jerusalén en 70 E.C., como atestigua Josefo."]},
 'JUAN': {"proposito":"Registrar señales y dichos para que los lectores creyeran que Jesús es el Cristo, el Hijo de Dios, y tuvieran vida.","contexto_historico":"Escrito por el apóstol Juan ya anciano, en Éfeso o cerca, hacia el año 98 E.C., después de su destierro en Patmos.","datos_interesantes":["El 92 % de su contenido es información suplementaria no considerada en los otros tres evangelios.","Destaca su prólogo sobre «la Palabra», que estaba en el principio con Dios.","Menciona cuatro Pascuas en el ministerio de Jesús, sosteniendo que duró tres años y medio.","El Papiro Rylands 457 apoya una composición a fines del primer siglo."]},
 'HECHOS': {"proposito":"Relatar la fundación y el crecimiento de la congregación cristiana mediante el espíritu santo, de los judíos a todas las naciones.","contexto_historico":"Escrito por Lucas hacia el fin de una estancia de dos años en Roma con Pablo, alrededor de 61 E.C., dirigido a Teófilo.","datos_interesantes":["Abarca unos 28 años (33–c. 61 E.C.); los 12 primeros capítulos se centran en Pedro y los 16 restantes en Pablo.","El cambio entre «ellos» y «nosotros» delata que Lucas fue compañero de viajes de Pablo.","Su exactitud la confirma la arqueología (templo de Ártemis, teatro de Éfeso).","Es canónico desde antiguo; partes aparecen en papiros de los siglos III–IV."]},
 'ROMANOS': {"proposito":"Establecer que judíos y no judíos son iguales ante Dios, declarados justos por fe, no por obras de la Ley.","contexto_historico":"Escrito por Pablo, con Tercio como secretario, desde Corinto hacia el fin de su tercer viaje, a principios de 56 E.C., camino a España.","datos_interesantes":["Dirigida a una congregación de Roma compuesta de cristianos judíos y no judíos.","Considera a fondo las dificultades por la presencia conjunta de judíos y griegos.","Cita abundantemente las Escrituras Hebreas.","Se halla en el Papiro Chester Beatty núm. 2, anterior a los códices Sinaítico y Vaticano."]},
 '1 CORINTIOS': {"proposito":"Corregir divisiones e inmoralidad y responder preguntas para restaurar espiritualmente a los corintios.","contexto_historico":"Escrito por Pablo desde Éfeso alrededor de 55 E.C., durante su tercera gira, tras recibir informes perturbadores de Corinto.","datos_interesantes":["Corinto era una ciudad próspera y moralmente decadente, con unos 400 000 habitantes.","Pablo había fundado la congregación de Corinto en una estancia de 18 meses hacia el año 50 E.C.","Aborda facciones, inmoralidad, matrimonio, alimentos a ídolos, la Cena del Señor y la resurrección.","Incluye la célebre defensa de la resurrección y el capítulo del amor."]},
 '2 CORINTIOS': {"proposito":"Consolar a los corintios tras su arrepentimiento y defender el apostolado de Pablo ante ataques de apóstoles falsos.","contexto_historico":"Escrito por Pablo desde Macedonia a fines del verano o principios del otoño de 55 E.C., poco después de la primera carta.","datos_interesantes":["Escrita alentado por el informe de Tito de que los corintios se habían arrepentido.","Enfrenta a los «apóstoles superfinos», apóstoles falsos que atacaban su autoridad.","Trata la generosidad para los santos necesitados y el principio «Dios ama al dador alegre».","Menciona su «espina en la carne» y la respuesta sobre la bondad inmerecida."]},
 'GÁLATAS': {"proposito":"Defender que la justificación viene por fe en Cristo, no por obras de la Ley, y que la circuncisión es innecesaria.","contexto_historico":"Escrito por Pablo contra judaizantes que perturbaban a las congregaciones gálatas, entre 50 y 52 E.C.","datos_interesantes":["Las congregaciones de Galacia incluían celtas o galos, formadas en el primer viaje de Pablo con Bernabé.","Es la única epístola que Pablo escribió personalmente «con grandes letras de su propia mano».","Prueba su apostolado y reprende a Pedro (Cefas) en Antioquía.","Explica el drama simbólico de Agar y Sara y aporta datos para la cronología bíblica."]},
 'EFESIOS': {"proposito":"Exhortar a los cristianos a mantener la unidad en Cristo y vestirse de la nueva personalidad.","contexto_historico":"Escrita por Pablo desde Roma, alrededor de 60-61 E.C., durante su primer encarcelamiento, y enviada con Tíquico.","datos_interesantes":["Dirigida a la congregación de Éfeso, ciudad célebre por su hechicería y el templo de Ártemis.","Algunos manuscritos omiten «en Éfeso», por lo que pudo ser una circular a Asia Menor.","El Papiro Chester Beatty núm. 2 y escritores como Ireneo confirman su autoría paulina.","Destaca el «secreto sagrado» de que judíos y gentiles serían coherederos en Cristo."]},
 'FILIPENSES': {"proposito":"Expresar agradecimiento y animar a los filipenses a mantener gozo, unidad y humildad.","contexto_historico":"Escrita por Pablo desde Roma alrededor de 60-61 E.C., prisionero custodio de la guardia pretoriana, por un don de los filipenses.","datos_interesantes":["Filipos era la ciudad principal de Macedonia, colonia romana, fundada en honor de Filipo II.","Pablo fundó la congregación hacia el año 50 E.C.; entre los primeros conversos estuvo Lidia.","Es la epístola más afectuosa de Pablo; agradece la generosidad de los filipenses.","Contiene la exhortación a tener «la misma actitud mental que Cristo»."]},
 'COLOSENSES': {"proposito":"Defender el conocimiento exacto y la superioridad de Cristo frente a filosofías paganas y tradiciones judías.","contexto_historico":"Escrita por Pablo desde la prisión en Roma entre 59-61 E.C., a raíz del informe de Epafras sobre Colosas.","datos_interesantes":["Colosas estaba en Frigia, junto a Laodicea y Hierápolis; la congregación era sobre todo de no judíos.","Fue despachada junto con la carta a Filemón, llevada por Tíquico y Onésimo.","Escrita al mismo tiempo que Efesios, con ideas y frases muy similares.","Recalca que Cristo es «la imagen del Dios invisible» y cabeza de la congregación."]},
 '1 TESALONICENSES': {"proposito":"Consolar y edificar en la fe a los tesalonicenses que sufrían persecución.","contexto_historico":"Escrita por Pablo desde Corinto a fines del año 50 E.C., tras recibir el informe alentador de Timoteo.","datos_interesantes":["Probablemente el primer escrito de Pablo en el canon; con excepción de Mateo, el primero de las Escrituras Griegas Cristianas.","La congregación de Tesalónica se estableció en la segunda gira de Pablo y sufrió severa persecución.","Su autenticidad la confirman el Fragmento Muratoriano, Ireneo y el Papiro Chester Beatty núm. 2.","Contiene la enseñanza sobre la esperanza de la resurrección en unión con Cristo."]},
 '2 TESALONICENSES': {"proposito":"Corregir el error de que la presencia del Señor era inminente y exhortar a estar firmes en la verdad.","contexto_historico":"Escrita por Pablo desde Corinto en el año 51 E.C., poco después de la primera carta, con Silvano y Timoteo.","datos_interesantes":["Corrige a quienes afirmaban que «el día de Jehová está aquí» y no trabajaban.","Enseña que antes vendría la apostasía y se revelaría «el hombre del desafuero».","Su autenticidad la atestiguan Ireneo y Justino Mártir.","Advierte apartarse de todo hermano desordenado que no ande según la tradición de Pablo."]},
 '1 TIMOTEO': {"proposito":"Fijar procedimientos de orden en la congregación, advertir contra las enseñanzas falsas y el materialismo en Éfeso.","contexto_historico":"Escrita desde Macedonia entre el primer y el último aprisionamiento de Pablo en Roma (61-64 E.C.), a Timoteo en Éfeso.","datos_interesantes":["Timoteo nació de padre griego y madre judía; lo incorporó Pablo en su segunda gira.","Timoteo es mencionado por nombre en 11 de las cartas de Pablo y en Hechos.","Detalla los requisitos de superintendentes y siervos ministeriales.","Advierte que «el amor al dinero es raíz de toda suerte de cosas perjudiciales»."]},
 '2 TIMOTEO': {"proposito":"Animar a Timoteo a efectuar plenamente su ministerio y predicar la palabra con urgencia.","contexto_historico":"Escrita en Roma alrededor de 65 E.C., durante el segundo aprisionamiento, poco antes del martirio de Pablo, bajo Nerón.","datos_interesantes":["Escrita bajo la amenaza de juicio y ejecución inminentes de Pablo.","Alaba a Onesíforo, quien lo buscó en Roma y no se avergonzó de sus cadenas.","Contiene que «toda Escritura es inspirada de Dios y provechosa».","Recuerda la fe sin hipocresía de la abuela Loida y la madre Eunice de Timoteo."]},
 'TITO': {"proposito":"Animar y dar apoyo autoritativo a Tito para corregir lo defectuoso y nombrar ancianos en Creta.","contexto_historico":"Escrita probablemente desde Macedonia, entre el primer y el segundo aprisionamiento de Pablo (61-64 E.C.), tras dejar a Tito en Creta.","datos_interesantes":["Tito era griego y acompañó varias veces a Pablo, incluida la colecta para Jerusalén.","El carácter mentiroso de los cretenses hacía necesaria una firme corrección.","Recoge los requisitos de los superintendentes para exhortar con enseñanza saludable.","Con 1 y 2 Timoteo forma las «cartas pastorales»; Ireneo y Orígenes las citan."]},
 'FILEMÓN': {"proposito":"Pedir a Filemón que recibiera amablemente a su esclavo fugitivo Onésimo, ya como hermano amado.","contexto_historico":"Escrita de propia mano en Roma durante el primer aprisionamiento (59-61 E.C.), enviada con Tíquico y Onésimo.","datos_interesantes":["Es la epístola más breve de Pablo y su única carta personal a una persona.","Filemón era acaudalado y vivía en Colosas; Onésimo significa «Provechoso».","Pablo se ofreció a cargar por su cuenta la injusticia de Onésimo.","Apeló al amor cristiano, no a un evangelio social contra la esclavitud."]},
 'HEBREOS': {"proposito":"Demostrar a los cristianos judíos que Cristo es superior a la Ley mosaica y cumplió lo que ella prefiguraba.","contexto_historico":"Escrita por Pablo desde Roma a los cristianos hebreos de Judea que sufrían intensa oposición judía, hacia 61 E.C.","datos_interesantes":["Argumenta la superioridad del sacerdocio de Cristo y del nuevo pacto sobre el de la Ley.","El capítulo 11 define la fe y recorre la «gran nube de testigos».","El Papiro Chester Beatty núm. 2 la coloca tras Romanos, respaldando la autoría de Pablo.","Escrita conforme a la comisión de Pablo de llevar el nombre de Jesús a los hijos de Israel."]},
 'SANTIAGO': {"proposito":"Exhortar a ser hacedores de la palabra y manifestar la fe mediante obras.","contexto_historico":"Escrita por Santiago, medio hermano de Jesús y columna de la congregación de Jerusalén, a las doce tribus esparcidas.","datos_interesantes":["Probablemente escrita poco antes de 62 E.C., año en que Anán apedreó a Santiago.","Complementa los argumentos de Pablo sobre la fe y las obras.","Usa ilustraciones como el freno y el timón sobre el poder de la lengua.","Aparece en los manuscritos Vaticano, Sinaítico y Alejandrino."]},
 '1 PEDRO': {"proposito":"Animar a los cristianos perseguidos a mantenerse firmes y conducirse con excelencia entre las naciones.","contexto_historico":"Escrita por Pedro desde Babilonia, entre 62 y 64 E.C., poco antes de la persecución de Nerón, a residentes de Asia Menor.","datos_interesantes":["Dirigida a judíos y no judíos esparcidos por Ponto, Galacia, Capadocia, Asia y Bitinia.","Escrita desde la Babilonia literal, a orillas del Éufrates, no desde Roma.","Eusebio, Ireneo, Orígenes y Tertuliano atestiguan su autenticidad.","Presenta a los cristianos como un sacerdocio real llamado a declarar las excelencias de Dios."]},
 '2 PEDRO': {"proposito":"Recordar que el conocimiento exacto mantiene firmes ante falsos maestros y el día de Jehová.","contexto_historico":"Escrita por Pedro alrededor de 64 E.C., poco después de la primera carta, sabiendo que pronto moriría.","datos_interesantes":["Pedro se identifica como testigo ocular de la transfiguración.","Advierte contra burladores que dudan de la presencia prometida de Cristo.","Enseña que mil años son para Jehová como un día.","Clasifica las cartas de Pablo con las demás Escrituras, como inspiradas por Dios."]},
 '1 JUAN': {"proposito":"Proteger a los cristianos de los anticristos y afianzarlos en el amor, la luz y la verdad.","contexto_historico":"Escrita por el apóstol Juan cerca de Éfeso alrededor de 98 E.C., para combatir la apostasía incipiente.","datos_interesantes":["Trata tres temas para refutar a los anticristos: el pecado, el amor y el anticristo.","No se dirige a una congregación particular, sino a toda la asociación cristiana.","Señala palabras añadidas tardíamente en 1 Juan 5:7, 8 sobre la Trinidad.","Su autenticidad la atestiguan el Fragmento Muratoriano, Ireneo, Policarpo y Papías."]},
 '2 JUAN': {"proposito":"Prevenir contra los engañadores y andar en la verdad con amor mutuo.","contexto_historico":"Escrita por el apóstol Juan, el anciano, desde Éfeso o sus alrededores, alrededor de 98 E.C.","datos_interesantes":["Dirigida a «la señora escogida» y a sus hijos, quizá una persona o una congregación.","Tan breve que pudo escribirse en una sola hoja de papiro.","Recomienda no recibir a quienes se adelantan más allá de la enseñanza de Cristo.","Ireneo y Clemente de Alejandría la citan; figura en el Fragmento Muratoriano."]},
 '3 JUAN': {"proposito":"Elogiar la hospitalidad de Gayo y aconsejar buenas obras ante la conducta de Diótrefes.","contexto_historico":"Escrita por el apóstol Juan, el anciano, desde Éfeso o cerca, alrededor de 98 E.C., a un fiel cristiano llamado Gayo.","datos_interesantes":["Dirigida personalmente a Gayo, amigo especial de Juan, por lo que usa «tú».","Expresa aprecio por la hospitalidad a hermanos viajantes.","Condena a Diótrefes, que se ensalzaba a sí mismo.","Da un vislumbre de la hermandad internacional de los cristianos primitivos."]},
 'JUDAS': {"proposito":"Exhortar a luchar tenazmente por la fe frente a hombres impíos infiltrados.","contexto_historico":"Escrita por Judas, medio hermano de Jesús y hermano de Santiago, alrededor de 65 E.C., probablemente desde Palestina.","datos_interesantes":["Judas se identifica humildemente como esclavo de Jesucristo, no como apóstol.","Advierte contra hombres que tomaban la bondad inmerecida como excusa para conducta relajada.","Usa ejemplos de israelitas infieles, ángeles caídos y Sodoma y Gomorra.","Su autenticidad la respaldan el Fragmento Muratoriano, Clemente, Orígenes y Tertuliano."]},
 'APOCALIPSIS': {"proposito":"Revelar mediante señales los propósitos de Dios para el futuro y culminar la santificación de su nombre.","contexto_historico":"Escrita por el apóstol Juan, desterrado en Patmos durante la persecución de Domiciano, alrededor de 96 E.C.","datos_interesantes":["Recibida por Jesucristo en señales mediante un ángel, no como revelación propia de Juan.","Contiene mensajes a las siete congregaciones de Asia Menor.","Ireneo señala que fue escrita a fines del reinado de Domiciano.","Se divide en dieciséis visiones que culminan en la Nueva Jerusalén."]},
}

def main():
    out = {"version": 1, "fuente": "Libros bíblicos (PDF) — sección introductoria de cada volumen", "libros": []}
    libros = out["libros"]
    for libro, cab in CAB.items():
        (escritor, lugar, lugar_incerto, inicio, fin, ini_est, fin_est, hecho_id,
         nombre, personajes, tipo, referencia) = cab
        c = CONTI.get(libro, {})
        entry = {
            "libro": libro,
            "nombre": nombre,
            "escritor": escritor,
            "personajes": personajes,
            "lugar_escritura": lugar,
            "lugar_incerto": lugar_incerto,
            "inicio": inicio,
            "fin": fin,
            "fecha_texto": ("c. " + str(inicio) + " e.c.") if inicio == fin else ("c. " + str(inicio) + " e.c."),
            "fecha_fin_texto": ("c. " + str(fin) + " e.c.") if fin != inicio else ("c. " + str(fin) + " e.c."),
            "ini_est": ini_est,
            "fin_est": fin_est,
            "tipo_suceso": tipo,
            "referencia": referencia,
            "fuente_pdf": nombre.split(' según')[0].split(',')[0] + " (libro bíblico), introducción",
            "proposito": c.get("proposito", ""),
            "contexto_historico": c.get("contexto_historico", ""),
            "datos_interesantes": c.get("datos_interesantes", []),
        }
        if hecho_id is not None:
            entry["hecho_id_existente"] = hecho_id
        libros.append(entry)

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'curacion', 'nt_escritura.json')
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    print('escrito:', path, '-', len(libros), 'libros')

if __name__ == '__main__':
    main()